### PR TITLE
Add a couple of ilianaw's services to http prom job

### PR DESCRIPTION
**Pull request by iliana**
hi

### CODE REVIEW

**Comment by euank** [comment]
Conclusions from some offline discussion:

Let's put these as a different job name to make it easier to dashboard/monitor em separately.

**Comment by euank** [comment]
Also, I didn't document this, but `prometheus-wob-prom-secret.yaml` is the file that matters, and is a base64-encoding of the file you edited.

I'll be fixing this messyness when I have a couple minutes to migrate it to helm (where I can have base64 encoding automagically happen and go back to one file).

**Comment by euank** [comment]
The file has moved to [here](https://github.com/euank/ek8s/blob/8e828c119b2e10bc8f2fa20bd05ff81d44f6755f/prometheus/wob/prometheus-config.yaml), and, unlike before, editing that file should be sufficient.

**Comment by iliana** [comment]
Per some IRC discussion I think I want to set this up on a different prom instance than the Wob one.

**Pull request closed without merging**
